// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT

mod aggregator;
pub use self::aggregator::{Aggregator, NONE_AGGREGATOR};

mod aggregator_pad;
pub use self::aggregator_pad::{AggregatorPad, NONE_AGGREGATOR_PAD};

mod enums;
pub use self::enums::AggregatorStartTimeSelection;

#[doc(hidden)]
pub mod traits {
    pub use super::aggregator::AggregatorExt;
    pub use super::aggregator_pad::AggregatorPadExt;
}
